package llm

import (
	"context"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
)

var (
	meter          = otel.Meter("github.com/nijaru/canto/llm")
	inputTokens    metric.Int64Counter
	outputTokens   metric.Int64Counter
	totalCostUsage metric.Float64Counter
	metricsOK      bool
)

func init() {
	var err error
	inputTokens, err = meter.Int64Counter(
		"gen_ai.usage.input_tokens",
		metric.WithDescription("Number of input tokens consumed by the LLM"),
		metric.WithUnit("{token}"),
	)
	if err != nil {
		return
	}

	outputTokens, err = meter.Int64Counter(
		"gen_ai.usage.output_tokens",
		metric.WithDescription("Number of output tokens generated by the LLM"),
		metric.WithUnit("{token}"),
	)
	if err != nil {
		return
	}

	totalCostUsage, err = meter.Float64Counter(
		"gen_ai.usage.cost",
		metric.WithDescription("Estimated cost of the LLM call in USD"),
		metric.WithUnit("USD"),
	)
	if err != nil {
		return
	}

	metricsOK = true
}

// RecordUsage emits OTel metric counters for a completed LLM call.
// modelID is the model identifier string (e.g. "gpt-4o").
// Call this after every successful Generate to keep metrics up to date.
func RecordUsage(ctx context.Context, modelID string, usage Usage) {
	if !metricsOK {
		return
	}
	attrs := metric.WithAttributes(attribute.String("gen_ai.request.model", modelID))
	inputTokens.Add(ctx, int64(usage.InputTokens), attrs)
	outputTokens.Add(ctx, int64(usage.OutputTokens), attrs)
	totalCostUsage.Add(ctx, usage.Cost, attrs)
}
