package llm

import (
	"context"

	"charm.land/catwalk/pkg/catwalk"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
)

var (
	meter          = otel.Meter("github.com/nijaru/canto/llm")
	inputTokens    metric.Int64Counter
	outputTokens   metric.Int64Counter
	totalCostUsage metric.Float64Counter
	metricsOK      bool
)

func init() {
	var err error
	inputTokens, err = meter.Int64Counter(
		"gen_ai.usage.input_tokens",
		metric.WithDescription("Number of input tokens consumed by the LLM"),
		metric.WithUnit("{token}"),
	)
	if err != nil {
		return
	}

	outputTokens, err = meter.Int64Counter(
		"gen_ai.usage.output_tokens",
		metric.WithDescription("Number of output tokens generated by the LLM"),
		metric.WithUnit("{token}"),
	)
	if err != nil {
		return
	}

	totalCostUsage, err = meter.Float64Counter(
		"gen_ai.usage.cost",
		metric.WithDescription("Estimated cost of the LLM call in USD"),
		metric.WithUnit("USD"),
	)
	if err != nil {
		return
	}

	metricsOK = true
}

// CalculateCost computes the cost of an LLM call based on token counts and model pricing.
func CalculateCost(model catwalk.Model, usage Usage) float64 {
	inputCost := float64(usage.InputTokens) * (model.CostPer1MIn / 1_000_000)
	outputCost := float64(usage.OutputTokens) * (model.CostPer1MOut / 1_000_000)
	return inputCost + outputCost
}

// Budget tracks cost accumulation and enforces limits.
type Budget struct {
	TotalCost float64
	Limit     float64
}

// IsExceeded returns true if the budget limit is reached.
func (b *Budget) IsExceeded() bool {
	return b.Limit > 0 && b.TotalCost >= b.Limit
}

// Add adds a usage record to the budget using model pricing.
func (b *Budget) Add(ctx context.Context, model catwalk.Model, usage Usage) {
	cost := CalculateCost(model, usage)
	b.TotalCost += cost

	if metricsOK {
		attrs := metric.WithAttributes(
			attribute.String("gen_ai.request.model", model.Name),
		)
		inputTokens.Add(ctx, int64(usage.InputTokens), attrs)
		outputTokens.Add(ctx, int64(usage.OutputTokens), attrs)
		totalCostUsage.Add(ctx, cost, attrs)
	}
}
